spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /platzi-market/api
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: pdn
server:
  port: 80
---