spring:
  profiles:
    active: dev
  #Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

server:
  servlet:
    context-path: /platzi-market/api


---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8090

---
spring:
  config:
    activate:
      on-profile: pdn
server:
  port: 80
---