spring:
  config:
    activate:
      on-profile: dev
---
spring:
  profiles:
    active: dev
  #Database
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1234
server:
  servlet:
    context-path: /platzi-market/api
  port: 8090

---
spring:
  config:
    activate:
      on-profile: pdn
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1234
server:
  servlet:
    context-path: /platzi-market/api
  port: 80
---